// <auto-generated />
using System;
using ContentHub.Modules.ContentSearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace ContentHub.Modules.ContentSearch.Infrastructure.Migrations
{
    [DbContext(typeof(ContentSearchDbContext))]
    partial class ContentSearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content_search")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentHub.Modules.ContentSearch.Domain.Model.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(description,''))", true);

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("content_type");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .HasDatabaseName("ix_content_items_fingerprint");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_content_items_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_content_items_content_type");

                    b.HasIndex("ProviderId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_content_items_provider_external");

                    b.ToTable("content_items", "content_search");
                });

            modelBuilder.Entity("ContentHub.Modules.ContentSearch.Domain.Model.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<short>("Format")
                        .HasColumnType("smallint")
                        .HasColumnName("format");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("providers", "content_search");
                });

            modelBuilder.Entity("ContentHub.Modules.ContentSearch.Domain.Model.ProviderFetchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("IncomingCount")
                        .HasColumnType("integer")
                        .HasColumnName("incoming_count");

                    b.Property<int>("NewCount")
                        .HasColumnType("integer")
                        .HasColumnName("new_count");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("updated_count");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_provider_fetch_runs_provider_started");

                    b.ToTable("provider_fetch_runs", "content_search");
                });

            modelBuilder.Entity("ContentHub.Modules.ContentSearch.Domain.Model.ContentItem", b =>
                {
                    b.OwnsOne("ContentHub.Modules.ContentSearch.Domain.Model.ContentMetrics", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("ContentItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("content_item_id");

                            b1.Property<long?>("Likes")
                                .HasColumnType("bigint")
                                .HasColumnName("likes");

                            b1.Property<long?>("Reactions")
                                .HasColumnType("bigint")
                                .HasColumnName("reactions");

                            b1.Property<int?>("ReadingTime")
                                .HasColumnType("integer")
                                .HasColumnName("reading_time");

                            b1.Property<long?>("Views")
                                .HasColumnType("bigint")
                                .HasColumnName("views");

                            b1.HasKey("ContentItemId");

                            b1.ToTable("content_metrics", "content_search");

                            b1.WithOwner()
                                .HasForeignKey("ContentItemId");
                        });

                    b.OwnsOne("ContentHub.Modules.ContentSearch.Domain.Model.ContentScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("ContentItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("content_item_id");

                            b1.Property<decimal>("BaseScore")
                                .HasColumnType("numeric")
                                .HasColumnName("base_score");

                            b1.Property<DateTimeOffset>("ComputedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("computed_at");

                            b1.Property<decimal>("EngagementScore")
                                .HasColumnType("numeric")
                                .HasColumnName("engagement_score");

                            b1.Property<decimal>("PersistentScore")
                                .HasColumnType("numeric")
                                .HasColumnName("persistent_score");

                            b1.Property<decimal>("TypeCoefficient")
                                .HasColumnType("numeric")
                                .HasColumnName("type_coefficient");

                            b1.HasKey("ContentItemId");

                            b1.HasIndex("PersistentScore")
                                .HasDatabaseName("ix_content_scores_persistent_score");

                            b1.ToTable("content_scores", "content_search");

                            b1.WithOwner()
                                .HasForeignKey("ContentItemId");
                        });

                    b.Navigation("Metrics")
                        .IsRequired();

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("ContentHub.Modules.ContentSearch.Domain.Model.Provider", b =>
                {
                    b.OwnsOne("ContentHub.Modules.ContentSearch.Domain.Model.RateLimitPolicy", "RateLimitPolicy", b1 =>
                        {
                            b1.Property<Guid>("ProviderId")
                                .HasColumnType("uuid");

                            b1.Property<short>("OverflowBehavior")
                                .HasColumnType("smallint")
                                .HasColumnName("overflow_behavior");

                            b1.Property<int>("RequestsPerMinute")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(60)
                                .HasColumnName("rate_limit_per_minute");

                            b1.HasKey("ProviderId");

                            b1.ToTable("providers", "content_search");

                            b1.WithOwner()
                                .HasForeignKey("ProviderId");
                        });

                    b.Navigation("RateLimitPolicy")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
