<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ContentHub.Modules.ContentSearch.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ContentHub.Modules.ContentSearch.Application\ContentHub.Modules.ContentSearch.Application.csproj" />
    <ProjectReference Include="..\ContentHub.Modules.ContentSearch.Domain\ContentHub.Modules.ContentSearch.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\ContentHub.BuildingBlocks.Infrastructure\ContentHub.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ContentHub.Modules.ContentSearch.IntegrationTests" />
  </ItemGroup>
</Project>
